login:
    path: /login
    defaults:
        _controller: YBUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

yb_ixina:
    resource: "@YBIxinaBundle/Resources/config/routing.yml"
    prefix:   /

yb_dash:
    resource: "@YBDashBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
