yb_ixina_homepage:
    path:     /
    defaults: 
        _controller: YBIxinaBundle:Ixina:home 

yb_ixina_newCustomer:
    path:    /customer/new/{origine}
    defaults:
        _controller: YBIxinaBundle:Customer:new

yb_ixina_modifCustomer:
    path:    /customer/modif/{id}/{origine}
    defaults:
        _controller: YBIxinaBundle:Customer:modif

yb_ixina_deleteCustomer:
    path:    /customer/supp/{id}
    defaults:
        _controller: YBIxinaBundle:Customer:supp

yb_ixina_vente:
    path:    /customer/vente/{id}
    defaults:
        _controller: YBIxinaBundle:Customer:vente

yb_ixina_tableau:
    path:    /tableau/home
    defaults:
        _controller: YBIxinaBundle:Tableau:home

yb_ixina_newNote:
    path:    /note/home
    defaults:
        _controller: YBIxinaBundle:Note:home 

yb_ixina_newRelCheq:
    path:    /note/RelanceCheque
    defaults:
        _controller: YBIxinaBundle:Note:newrelcheque

yb_ixina_consultRelCheq:
    path:    /note/ConsultRelancesCheques
    defaults:
        _controller: YBIxinaBundle:Note:consultrelcheq

yb_ixina_modifRelCheq:
    path:    /note/ModifRelanceCheque/{id}
    defaults: 
        _controller: YBIxinaBundle:Note:modifrelcheq

yb_ixina_relsupp:
    path:    /note/SupprimeRelance/{id}
    defaults:
        _controller: YBIxinaBundle:Note:supprelcheq

yb_ixina_newPlanTech:
    path:    /note/PlanTechnique
    defaults:
        _controller: YBIxinaBundle:Note:newplantech

yb_ixina_consultPlanTech:
    path:    /note/ConsultPlanTech 
    defaults:
        _controller: YBIxinaBundle:Note:consultplantech

yb_ixina_plansupp:
    path:    /note/SuppPlanTech/{id}
    defaults:
        _controller: YBIxinaBundle:Note:suppplantech

yb_ixina_newFacturation:
    path:    /note/Facturation 
    defaults: 
        _controller: YBIxinaBundle:Note:newfacture

yb_ixina_consultFacturation:
    path:    /note/ConsultFacturation
    defaults:
        _controller: YBIxinaBundle:Note:consultfacture

yb_ixina_suppfacture:
    path:    /note/SuppFacture/{id}
    defaults:
        _controller: YBIxinaBundle:Note:suppfacture

yb_ixina_newPrestation:
    path:    /note/Prestation 
    defaults:
        _controller: YBIxinaBundle:Note:newprestation

yb_ixina_listePrestation:
    path:    /note/ListePrestation 
    defaults:
        _controller: YBIxinaBundle:Note:listeprestation

yb_ixina_modifPrestation:
    path:    /note/modifPrestation/{id}
    defaults: 
        _controller: YBIxinaBundle:Note:modifprestation

yb_ixina_prestationsupprimer:
    path:    /note/suppPrestation/{id}
    defaults:
        _controller: YBIxinaBundle:Note:suppprestatation