services:
    yb_ixina.doctrineListener:
        class: YB\IxinaBundle\DoctrineListener
        arguments:
            - "@yb_popup.test"
        tags:
            - { name: doctrine.event_listener, event: postPersist }