<?php

namespace YB\IxinaBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function ClientsToday()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->Where('c.dateProchaineAction = :today')
            ->setParameter('today', new \DateTime(date('Y-m-d')))
            ;
        return $qb->getQuery()->getResult();
    }

    public function ClientsByDateAction()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->orderBy('c.dateProchaineAction', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function ProspectByDateAction()
    {
        $qb = $this->createQueryBuilder('c')
            ->Where('c.etatDossier = :etat')
            ->setParameter('etat', 'Prospect')
            ->orderBy('c.dateProchaineAction', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function ClientsDessin()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->Where('c.dessin = :dessin')
            ->setParameter('dessin', false)
            ->orderBy('c.dateProchaineAction', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function ClientsPreparer()
    {
        $qb = $this->createQueryBuilder('c')
        ->Where('c.preparation = :preparation')
        ->setParameter('preparation', false)
        ->orderBy('c.dateProchaineAction', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function firstDessin()
    {
        $qb = $this->createQueryBuilder('c')
            ->Where('c.dessin = :dessin')
            ->setParameter('dessin', false)
            ->orderBy('c.dateProchaineAction', 'ASC');
            return $qb->getQuery()->getResult();
    }

    public function firstPreparation()
    {
        $qb = $this->createQueryBuilder('c')
            ->Where('c.preparation = :preparation')
            ->setParameter('preparation', false)
            ->orderBy('c.dateProchaineAction', 'ASC');
            return $qb->getQuery()->getResult();
    }

    public function ClientsPerduMoisEnCours()
    {
        $qb = $this->createQueryBuilder('c')
            ->Where('c.etatDossier = :etat')
            ->setParameter('etat', 'Perdu')
            ->orderBy('c.dateProchaineAction', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function ClientsVenduMoisEnCours()
    {
        $qb = $this->createQueryBuilder('c')
            ->Where('c.etatDossier = :etat')
            ->setParameter('etat', 'Vendu')
            ->orderBy('c.dateProchaineAction', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function ClientsProspectMoisEnCours()
    {
        $qb = $this->createQueryBuilder('c')
            ->Where('c.etatDossier = :etat')
            ->setParameter('etat', 'Prospect')
            ->orderBy('c.dateProchaineAction', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function ClientsRetourDuMois()
    {
         $qb = $this->createQueryBuilder('c')
            ->Where('c.etatDossier = :etat')
            ->setParameter('etat', 'Prospect')
            ->andWhere('c.action = :action')
            ->setParameter('action', 'Retour')
            ->orderBy('c.dateProchaineAction', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
