<?php

namespace YB\IxinaBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function ClientsToday()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->Where('c.dateProchaineAction = :today')
            ->setParameter('today', new \DateTime(date('Y-m-d')))
            ;
        return $qb->getQuery()->getResult();
    }

}
