<?php

namespace YB\IxinaBundle\Repository;

/**
 * DossierMetreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierMetreRepository extends \Doctrine\ORM\EntityRepository
{
}
