<?php

namespace YB\IxinaBundle\Repository;

/**
 * PlanPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanPrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
