<?php

namespace YB\IxinaBundle\Repository;

/**
 * PlantechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantechRepository extends \Doctrine\ORM\EntityRepository
{
}
