<?php

namespace YB\IxinaBundle\Repository;

/**
 * RelChequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelChequeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllRel()
    {
        $qb = $this->createQueryBuilder('r')
            ->orderBy('r.dateRelance', 'ASC')
            ;
        return $qb->getQuery()->getResult();
    }

    public function relanceToday()
    {
        $today = new \dateTime('now');
        $qb = $this->createQueryBuilder('r')
            ->Where('r.dateRelance <= :today')
            ->setParameter('today', $today)
            ->orderBy('r.dateRelance', 'ASC')
            ;
        return $qb->getQuery()->getResult();
    }
}
