<?php

namespace YB\IxinaBundle\Repository;

/**
 * TacheParticuliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheParticuliereRepository extends \Doctrine\ORM\EntityRepository
{
}
